### ISSUE TITLE
 Consider documenting our "Tech Review" process

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/practices#16]
I believe it's already documented in Loop (and I don't want to duplicate that documentation) but would be good to at least point to that Loop page from `practices`

**Comment by AlexAxthelm** [comment]
cc @hodie

**Comment by hodie** [comment]
Also happy to move it to `practices`. Loop makes some sense for general stuff. But mostly it's just where I love to write because I can use md and don't have to worry about presentation. I think it makes sense for tech team stuff to live in one place.

**Comment by AlexAxthelm** [comment]
I would be 💯 down to open issues for tech reviews here. Or maybe we would have a `tech-stack` repo that would make sense as a companion to practices (policy vs customs)?

**Comment by jdhoffa** [comment]
Just to clarify, the definition of the "tech review process" is something I would document in `practices`, but the actual: {calls, transcripts, decisions} etc. I think should live somewhere else. This could be the Loop page as-is if it is working well, or some new `tech-stack` repo, either way, I can add a link in the process documentation.  

Mainly I envision this repo as something that we can give to a new employee as onboarding material:
"these are our expectations, this is how we work together and operate and communicate". 

But details on the tech stack (e.g. We want to use JSON for input parameters) would for sure be out of scope.

**Comment by AlexAxthelm** [comment]
> But details on the tech stack (e.g. We want to use JSON for input parameters) would for sure be out of scope.

Agree that those probably shouldn't live here, but it would be a good idea to have our cross-repo `conventions|policies|architecture|design philosphy]` somewhere that's public (not Loop/SharePoint), so that we can point to the "big picture" when we need to.

**Comment by jdhoffa** [comment]
Absolutely!

**Comment by jdhoffa** [comment]
But in general, I think the best way to view this is as an onboarding document (of course it is more than that). It helps to really make clear what is in and out of scope I think

**Comment by jdhoffa** [comment]
I don't think this is entirely necessary anymore. 
We have two main tech calls:
`devHangouts` and `Tech Review`

the former is focused on social aspects fo software development
the latter is focused on technical decision-making (specific architecture questions etc.)

I don't necessarily think either of these need to be documented in the https://github.com/RMI-PACTA/practices repo
