### ISSUE TITLE
Branch protection rules vs rulesets

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/practices#30]
It seems that GitHub offers two separate mechanisms for protecting branches:

* [Branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)
* [Rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets#about-rulesets-protected-branches-and-protected-tags)

Rulesets is newer, and seems to have some advantages (multiple rulesets can apply to a branch, different rules available, can be defined once as a JSON and imported across repos).

Importantly, rulesets are visible and accessible through the API, meaning that we could set up an action to check if they're enabled (in the housekeeping set?)

We should explore if switching would be worth it.

**Comment by jdhoffa** [comment]
This sounds reasonable and interesting as an option, but functionally "what tool we use to manage branch protections" is too specific for the `practices` repo. Happy to leave the issue open for further discussion, but I will tag this as "wontfix".

Remember, in `practices` we "focus on the *what* and *why* with only optional resources on the *how*" to avoid being needlessly prescriptive:

https://github.com/RMI-PACTA/practices/blob/22efb510804501b282c1637773d2d31965cc7c75/README.md?plain=1#L5
